//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INV01.DO.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv01_bitacora_producto
    {
        public decimal idbitacora { get; set; }
        public Nullable<decimal> idproducto { get; set; }
        public string descripcion_anterior { get; set; }
        public string descripcion_actual { get; set; }
        public Nullable<decimal> precio_costo_anterior { get; set; }
        public Nullable<decimal> precio_costo_actual { get; set; }
        public byte[] imagen_anterior { get; set; }
        public byte[] imagen_actual { get; set; }
        public string estado_registro_anterior { get; set; }
        public string estado_registro_actual { get; set; }
        public string usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    }
}
