//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INV01.DO.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv01_producto
    {
        public inv01_producto()
        {
            this.inv01_inventario = new HashSet<inv01_inventario>();
            this.inv01_inventario_movimiento = new HashSet<inv01_inventario_movimiento>();
            this.inv01_producto_perdida = new HashSet<inv01_producto_perdida>();
        }
    
        public decimal idproducto { get; set; }
        public string codigo_barra { get; set; }
        public Nullable<decimal> idcategoria { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> precio_costo { get; set; }
        public byte[] imagen { get; set; }
        public string estado_registro { get; set; }
        public string usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public string usuario_anulacion { get; set; }
        public Nullable<System.DateTime> fecha_nulacion { get; set; }
    
        public virtual inv01_categoria inv01_categoria { get; set; }
        public virtual ICollection<inv01_inventario> inv01_inventario { get; set; }
        public virtual ICollection<inv01_inventario_movimiento> inv01_inventario_movimiento { get; set; }
        public virtual ICollection<inv01_producto_perdida> inv01_producto_perdida { get; set; }
    }
}
