//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INV01.DO.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv01_movimiento
    {
        public inv01_movimiento()
        {
            this.inv01_envio_detalle = new HashSet<inv01_envio_detalle>();
            this.inv01_envio_encabezado = new HashSet<inv01_envio_encabezado>();
        }
    
        public decimal idmovimiento { get; set; }
        public string idtipo_mov { get; set; }
        public Nullable<decimal> idtipo_pago { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public string cantidad_letras { get; set; }
        public string estado_registro { get; set; }
        public string usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public string usuario_anulacion { get; set; }
        public Nullable<System.DateTime> fecha_nulacion { get; set; }
    
        public virtual ICollection<inv01_envio_detalle> inv01_envio_detalle { get; set; }
        public virtual ICollection<inv01_envio_encabezado> inv01_envio_encabezado { get; set; }
        public virtual inv01_tipo_movimiento inv01_tipo_movimiento { get; set; }
        public virtual inv01_tipo_pago inv01_tipo_pago { get; set; }
    }
}
