//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INV01.DO.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv01_inventario_movimiento
    {
        public decimal idmovimiento { get; set; }
        public Nullable<decimal> idproducto { get; set; }
        public string descripcion_producto { get; set; }
        public Nullable<decimal> idtipo_mov_inv { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> numero_envio { get; set; }
        public Nullable<decimal> habia { get; set; }
        public Nullable<decimal> hay { get; set; }
        public Nullable<decimal> existencia { get; set; }
        public string estado_registro { get; set; }
        public string usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public string usuario_anulacion { get; set; }
        public Nullable<System.DateTime> fecha_nulacion { get; set; }
    
        public virtual inv01_producto inv01_producto { get; set; }
        public virtual inv01_tipo_mov_inventario inv01_tipo_mov_inventario { get; set; }
    }
}
