//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INV01.DO.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv01_cliente
    {
        public inv01_cliente()
        {
            this.inv01_envio_encabezado = new HashSet<inv01_envio_encabezado>();
        }
    
        public decimal idcliente { get; set; }
        public string nit { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string nombre_completo { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string estado_registro { get; set; }
        public string usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public string usuario_anulacion { get; set; }
        public Nullable<System.DateTime> fecha_nulacion { get; set; }
    
        public virtual ICollection<inv01_envio_encabezado> inv01_envio_encabezado { get; set; }
    }
}
