//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INV01.DO.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv01_envio_encabezado
    {
        public inv01_envio_encabezado()
        {
            this.inv01_envio_detalle = new HashSet<inv01_envio_detalle>();
        }
    
        public decimal idenvio { get; set; }
        public Nullable<decimal> envio { get; set; }
        public Nullable<decimal> idmovimiento { get; set; }
        public Nullable<decimal> idcliente { get; set; }
        public Nullable<decimal> total { get; set; }
        public string total_letras { get; set; }
        public string estado_registro { get; set; }
        public string usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public string usuario_anulacion { get; set; }
        public Nullable<System.DateTime> fecha_nulacion { get; set; }
    
        public virtual inv01_cliente inv01_cliente { get; set; }
        public virtual ICollection<inv01_envio_detalle> inv01_envio_detalle { get; set; }
        public virtual inv01_movimiento inv01_movimiento { get; set; }
    }
}
