//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INV01.DO.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv01_usuario
    {
        public inv01_usuario()
        {
            this.inv01_usuario_correlativo = new HashSet<inv01_usuario_correlativo>();
            this.inv01_usuario_rol = new HashSet<inv01_usuario_rol>();
        }
    
        public string usuario { get; set; }
        public string nombre { get; set; }
        public string password { get; set; }
        public string estado_registro { get; set; }
        public string usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public string usuario_anulacion { get; set; }
        public Nullable<System.DateTime> fecha_nulacion { get; set; }
    
        public virtual ICollection<inv01_usuario_correlativo> inv01_usuario_correlativo { get; set; }
        public virtual ICollection<inv01_usuario_rol> inv01_usuario_rol { get; set; }
    }
}
